[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "whatsapp-campaign-manager"

[services.source]
repo = "."

[services.variables]
NODE_ENV = "production"
PORT = "5000"